[tools]
lefthook = 'latest'

[tasks.svcheck]
run = '''
uv run https://raw.githubusercontent.com/mustafa0x/util/main/svcheck.py
pnpm exec prettier --write '**/*.{js,ts,svelte,json}' --write
CHANGED=$(git diff --diff-filter=d --name-only HEAD)
[ -z "$CHANGED" ] || pnpm exec eslint --fix $CHANGED
'''
