on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3

      - run: pnpm install --frozen-lockfile
      - run: pnpm -s build
      - run: npm publish
